{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "sematic-server.labels" . | nindent 4 }}
    {{- if .Values.deployment.socket_io.dedicated }}
    app.kubernetes.io/component: api
    {{- else }}
    app.kubernetes.io/component: all
    {{- end }}
  annotations:
    {{- if .Values.gcp.enabled }}
    {{- if .Values.ingress.create }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
    {{- end }}
    {{- with .Values.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sematic-server.selectorLabels" . | nindent 4 }}
    {{- if .Values.deployment.socket_io.dedicated }}
    sematic.ai/component: api
    {{- else }}
    sematic.ai/component: all
    {{- end }}
{{- end }}
